needle_project/home/urls.py
from django.urls import path
from home import views
from home.views import UserPostView,CreatePostView,DetailView,UserAboutView,DeletePostView,UpdatePostView

urlpatterns = [
    path('', views.index, name='home'),
    path('createpost/',CreatePostView.as_view(), name='createpost'),
    path('post/<int:pk>/update', UpdatePostView.as_view(), name='updatepost'),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name='deletepost'),
    path('<str:username>/about/', UserAboutView.as_view(), name='about'),
    path('<str:username>/post/<int:pk>/', DetailView.as_view(), name='detailpost'),
    path('<str:username>/', UserPostView.as_view(), name='userpost'),
    path('<str:username>/like_post/<int:post_id>/', views.like_post, name='like_post'),



]

needle_project/needle_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('home.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

needle_project/home/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='post-pictures', default='defaultimage.png')
    time = models.DateTimeField(default=timezone.now)
    is_deletable = models.BooleanField(default=True)

    def delete(self, *args, **kwargs):
        if self.is_deletable:
            super().delete(*args, **kwargs)

    def __str__(self):
        return f'{self.author} Post'

    def get_absolute_url(self):
        return reverse("detailpost", kwargs={"username": self.author.username, "pk": self.pk})

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('home.Post', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} likes {self.post}'

needle_project/home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView, DetailView, CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from home.models import Post,Like
from django.contrib.auth.models import User


@login_required(login_url="login")
def index(request):
    posts = Post.objects.all().order_by('-time')
    context = {
        'posts': posts,
    }
    return render(request, 'index.html', context)


def like_post(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    like, created = Like.objects.get_or_create(user=request.user, post=post)
    if not created:
        like.delete()
    else:
        like

    return redirect('detailpost', username=username, pk=post_id)



class UserAboutView(LoginRequiredMixin, ListView ):
    model=Post
    template_name='about.html'
    context_object_name='posts'

    def get_queryset(self):
        user=get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user)


class UserPostView(LoginRequiredMixin, ListView ):
    model=Post
    template_name='profile.html'
    context_object_name='posts'


    def get_queryset(self):
        user=get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-time')

class DetailView(LoginRequiredMixin, DetailView):
    model=Post
    template_name='detailpost.html'
    context_object_name='posts'



class CreatePostView(LoginRequiredMixin, CreateView):
    model=Post
    template_name='createpost.html'
    fields=['content', 'image']

    def form_valid(self, form):
        form.instance.author=self.request.user
        return super().form_valid(form)

class UpdatePostView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model=Post
    template_name='updatepost.html'
    fields=['content', 'image']
    success_url=''


    def test_func(self):
        post = self.get_object()
        if post.author==self.request.user:
            return True
        else:
            return False

class DeletePostView(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
    model=Post
    template_name='deletepost.html'
    success_url='/'


    def test_func(self):
        post=self.get_object()
        if post.author==self.request.user:
            return True
        else:
            return False






needle_project/home/templates/about.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}

{% for post in posts %}
{% if forloop.first %}
  <main>
    <!-- Container START -->
    <div class="container">
      <div class="row g-4">

        <!-- Main content START -->
        <div class="col-lg-8 vstack gap-4">
          <!-- My profile START -->

          <div class="card">
            <!-- Cover image -->
            <div class="h-200px rounded-top" style="background-image:url(assets/images/bg/05.jpg); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
              <!-- Card body START -->
              <div class="card-body py-0">
                <div class="d-sm-flex align-items-start text-center text-sm-start">
                  <div>
                    <!-- Avatar -->
                    <div class="avatar avatar-xxl mt-n5 mb-3">

                      <img class="avatar-img rounded-circle border border-whituserprofilee border-3" src="{{post.author.userprofile.image.url}}" alt="">
                    </div>
                  </div>
                  <div class="ms-sm-4 mt-sm-3">
                    <!-- Info -->
                    <h1 class="mb-0 h5">{{post.author.get_full_name}}<i class="bi bi-patch-check-fill text-success small"></i></h1>
                    <p>250 connections</p>
                  </div>
                  <!-- Button -->
                  <div class="d-flex mt-3 justify-content-center ms-sm-auto">
                    {% if post.author == request.user %}
                    <button class="btn btn-danger-soft me-2" type="button"> <i class="bi bi-pencil-fill pe-1"></i> Edit profile </button>
                    {% endif %}
                  </div>
                </div>
                <!-- List profile -->
                <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">

                  <li class="list-inline-item"><i class="bi bi-calendar2-plus me-1"></i> Joined On {{request.user.date_joined|date:"F d, Y"}}</li>
                </ul>
              </div>
              <!-- Card body END -->
              <div class="card-footer mt-3 pt-2 pb-0">
                <!-- Nav profile pages -->
                <ul class="nav nav-bottom-line align-items-center justify-content-center justify-content-md-start mb-0 border-0">
                  <li class="nav-item"> <a class="nav-link " href="{% url "userpost" post.author.username %}"> Posts </a> </li>
                  <li class="nav-item"> <a class="nav-link active" href="{% url "about" post.author.username %}"> About </a> </li>

                </ul>
              </div>
            </div>
            <div class="col-lg-4">

              <div class="row g-4">

                <!-- Card START -->
                <div class="col-md-6 col-lg-12">
                  <div class="card">
                    <div class="card-header border-0 pb-0">
                      <h5 class="card-title">About</h5>
                      <!-- Button modal -->
                    </div>
                    <!-- Card body START -->
                    <div class="card-body position-relative pt-0">
                      <p>{{post.author.userprofile.intro}}</p>
                      <!-- Date time -->
                      <ul class="list-unstyled mt-3 mb-0">

                        <li> <i class="bi bi-envelope fa-fw pe-1"></i> Email: <strong> {{post.author.email}} </strong> </li>
                      </ul>
                    </div>
                    <!-- Card body END -->
                  </div>
                </div>
                <!-- Card END -->
              </div>

            </div>
          </main>


            <!-- My pro
              file END -->
            {% endif %}
              {% endfor %}


            <!-- Share feed START -->





{% endblock body %}

needle_project/home/templates/createpost.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <!-- Container START -->
    <div class="container">
      <div class="row">
  
        <!-- Sidenav START -->
        <div class="col-lg-3">
  
          <!-- Advanced filter responsive toggler START -->
                  <!-- Divider -->
                  <div class="d-flex align-items-center mb-4 d-lg-none">
                      <button class="border-0 bg-transparent" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                          <span class="btn btn-primary"><i class="fa-solid fa-sliders-h"></i></span>
              <span class="h6 mb-0 fw-bold d-lg-none ms-2">Settings</span>
                      </button>
                  </div>
                  <!-- Advanced filter responsive toggler END -->
  
          <nav class="navbar navbar-light navbar-expand-lg mx-0">
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar">
              <!-- Offcanvas header -->
                          <div class="offcanvas-header">
                              <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                          </div>
  
              <!-- Offcanvas body -->
              <div class="offcanvas-body p-0">
                <!-- Card START -->
                <div class="card w-100">
                  <!-- Card body START -->
                  <div class="card-body">
  
                  <!-- Side Nav START -->
                  <ul class="nav nav-tabs nav-pills nav-pills-soft flex-column fw-bold gap-2 border-0" role="tablist">
                    <li class="nav-item" data-bs-dismiss="offcanvas" role="presentation">
                      <a class="nav-link d-flex mb-0 active" href="{% url "setting" %}" data-bs-toggle="tab" aria-selected="true" role="tab"> <span>Create post </span></a>
                    </li>
                 
                   
                    </li>
                  </ul>
                  <!-- Side Nav END -->
  
                </div>
            
                </div>
              <!-- Card END -->
              </div>
              <!-- Offcanvas body -->
  
              <!-- Helper link START -->
              <ul class="nav small mt-4 justify-content-center lh-1">
                <li class="nav-item">
                  <a class="nav-link" href="my-profile-about.html">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="settings.html">Settings</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://support.webestica.com/login">Support </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="docs/index.html">Docs </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="help.html">Help</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="privacy-and-terms.html">Privacy &amp; terms</a>
                </li>
              </ul>
              <!-- Helper link END -->
              <!-- Copyright -->
              <p class="small text-center mt-1">©2023 <a class="text-reset" target="_blank" href="#"> Gaurab Lohani </a></p>
            
            </div>
          </nav>
        </div>
        <!-- Sidenav END -->
  
          <!-- Main content START -->
          <div class="col-lg-6 vstack gap-4">
            <!-- Setting Tab content START -->
            <div class="tab-content py-0 mb-0">
  
              <!-- Account setting tab START -->
              <div class="tab-pane show active fade" id="nav-setting-tab-1" role="tabpanel">
                <!-- Account settings START -->
                <div class="card mb-4">
                  
                  <!-- Title START -->
                  <div class="card-header border-0 pb-0">
                    <h1 class="h5 card-title">Create a Post</h1>
                  </div>
                  <!-- Card header START -->
                  <!-- Card body START -->
                  <div class="card-body">
                    <!-- Form settings START -->
                    <form  class="row g-3" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                        <!-- First name -->
                      <div class="col-sm-6 col-lg-4">
                        {{ form.content|as_crispy_field }}
                      </div>
             
                      <div class="col-12">
                        {{ form.image|as_crispy_field }}

                      </div>
                  
                      <!-- Button  -->
                      <div class="col-12 text-end">
                        <button type="submit" class="btn btn-sm btn-primary mb-0">Save changes</button>
                      </div>
                    </form>
                    <!-- Settings END -->
                  </div>
                <!-- Card body END -->
                </div>
                <!-- Account settings END -->
  
  
            </div>
            <!-- Setting Tab content END -->
          </div>
  
      </div> <!-- Row END -->
    </div>
    <!-- Container END -->
  
  </main>
{% endblock body %}



{% comment %} {% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
<main>
  <div class="container">
    <div class="col-md-8 col-lg-6 vstack gap-4">
<div class="card">
  <div class="card-header border-0 pb-0">
      <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
              <!-- Avatar -->
              <div class="avatar avatar-story me-2">
                  <a href="#!">  
                  
                  <img src="{{ request.user.userprofile.image.url }}" alt="{{ request.user.username }} profile picture">

              </a>
              </div>
              <!-- Info -->
              <div>
                  <div class="nav nav-divider">
                      <h6 class="nav-item card-title mb-0"> <a href="{% url 'userpost' request.user.username %}"> {{request.user.get_full_name}} </a></h6>
                      
                  </div>
                 
              </div>
          </div>
          <!-- Card feed action dropdown START -->
          <div class="dropdown">
              <a href="#" class="text-secondary btn btn-secondary-soft-hover py-1 px-2"
                  id="cardFeedAction" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bi bi-three-dots"></i>
              </a>
              <!-- Card feed action dropdown menu -->
         
          </div>
          <!-- Card feed action dropdown END -->
      </div>
  </div>

  <div class="card-body">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">

          <legend class="border-bottom mb-4">Create Post</legend>
          {{ form|crispy }}

      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Create</button>
      </div>
  </form>
 

      </div>

  </div>



 

   

</div>
</main>
</div>
</div>
{% endblock body %} {% endcomment %}

needle_project/home/templates/deletepost.html
{% extends "base.html" %}
{% block body %}
<main>
    <div class="container">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
               
            </div>
        </form>
    </div>
</main>
</div>
{% endblock body %}

needle_project/home/templates/detailpost.html
{% extends "base.html" %}
{% block body %}
<main>
 <div class="container">
    <div class="card mb-4">
        <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                    <!-- Avatar -->
                    <div class="avatar avatar-story me-2">
                        <a href="#">
                            <img class="avatar-img rounded-circle" src="{{ object.author.userprofile.image.url }}" alt="">
                        </a>
                    </div>

                    <!-- Info -->
                    <div>
                        <div class="nav nav-divider">
                            <h6 class="nav-item card-title mb-0">
                                <a href="{% url 'userpost' object.author.username %}">{{ object.author.get_full_name }}</a>
                            </h6>
                        </div>
                        <p class="mb-0 small text-muted">{{ object.time|date:"F j, Y" }}</p>

                    </div>
                </div>
                <!-- Card feed action dropdown START -->
                <div class="dropdown">
                    <a href="#" class="text-secondary btn btn-secondary-soft-hover py-1 px-2" id="cardFeedAction"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-three-dots"></i>
                    </a>
                    <!-- Card feed action dropdown menu -->
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="cardFeedAction">
                       {% if object.author == request.user %}
                            {% if object.is_deletable %}
                                <li><a class="dropdown-item" href="{% url "updatepost" object.id %}"><i
                                            class="bi bi-pencil-square"></i> Edit Post</a></li>
                                <li><a class="dropdown-item" href="{% url "deletepost" object.id %}"><i
                                            class="bi bi-trash"></i> Delete Post</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="#" disabled><i class="bi bi-exclamation-circle"></i> Cannot delete this post</a></li>
                            {% endif %}
                        {% else %}
                            <li><a class="dropdown-item" href="#" disabled><i class="bi bi-exclamation-circle"></i> Not Authorized</a></li>
                        {% endif %}
                    </ul>
                </div>
                <!-- Card feed action dropdown END -->
            </div>
        </div>

        <div class="card-body">
            {% if object.image.url %}
                <p class="card-text mb-3">{{ object.content }}</p>

                    <img class="card-img custom-img-height" src="{{ object.image.url }}" alt=''>

            {% else %}
                <p class="card-text">{{ object.content }}</p>
            {% endif %}

            <!-- Feed react START -->
            <div class="d-flex justify-content-between align-items-center mt-3">
                <div class="d-flex">

<form id="like-form" method="GET" action="{% url 'like_post' object.author.username object.id %}">
    {% csrf_token %}
    <button type="submit" class="text-primary me-3" style="border: none; background-color: transparent;">
        <i class="bi bi-hand-thumbs-up"></i> Like ({{ object.like_set.count }})
    </button>
</form>
                </div>
                <div>
                    <a href="#" class="text-secondary">
                        <i class="bi bi-share"></i> Share
                    </a>
                </div>
            </div>
            <!-- Feed react END -->
        </div>

</main>
<style>
    .custom-img-height {
        max-height: 100vh;
        width: auto;
        display: block;
        margin: auto;
    }
</style>
{% endblock body %}

needle_project/home/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}

{% if posts %}
  {% for post in posts %}
    {% if forloop.first %}
      <main>
        <!-- Container START -->
        <div class="container">
          <div class="row g-4">

            <!-- Main content START -->
            <div class="col-lg-8 vstack gap-4">
              <!-- My profile START -->

              <div class="card">
                <!-- Cover image -->
                <div class="h-200px rounded-top"
                  style="background-image:url({{post.author.userprofile.background_cover.url}}); background-position: center; background-size: cover; background-repeat: no-repeat;">
                </div>
                <!-- Card body START -->
                <div class="card-body py-0">
                  <div class="d-sm-flex align-items-start text-center text-sm-start">
                    <div>
                      <!-- Avatar -->
                      <div class="avatar avatar-xxl mt-n5 mb-3">

                        <img class="avatar-img rounded-circle border border-whituserprofilee border-3"
                          src="{{post.author.userprofile.image.url}}" alt="">
                      </div>
                    </div>
                    <div class="ms-sm-4 mt-sm-3">
                      <!-- Info -->
                      <h1 class="mb-0 h5">{{post.author.get_full_name}}

                        {% if post.author.is_staff %}
                          <i class="bi bi-patch-check-fill text-success small"></i></h1>
                        {% endif %}
                    </div>
                    <!-- Button -->
                    <div class="d-flex mt-3 justify-content-center ms-sm-auto">
                      {% if post.author == request.user %}
                        <a href="{% url "setting" %}">
                          <button class="btn btn-danger-soft me-2" type="button"> <i
                              class="bi bi-pencil-fill pe-1"></i> Edit profile </button></a>
                      {% endif %}
                    </div>
                  </div>
                  <!-- List profile -->
                  <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
                      <li class="list-inline-item">
    <span class="bi bi-pencil"></span> Total Posts = {{ posts|length }}
</li>

     <li class="list-inline-item">
</li>
  <li class="list-inline-item"></li></li>
<li class="list-inline-item"><i class="bi bi-briefcase me-1"></i> Joined On  {{request.user.date_joined|date:"F d, Y"}}</li>


                  </ul>
                </div>
                <!-- Card body END -->
                <div class="card-footer mt-3 pt-2 pb-0">
                  <!-- Nav profile pages -->
                  <ul
                    class="nav nav-bottom-line align-items-center justify-content-center justify-content-md-start mb-0 border-0">
                    <li class="nav-item"> <a class="nav-link active" href="my-profile.html"> Posts </a> </li>
                    <li class="nav-item"> <a class="nav-link" href="{% url "about" post.author.username %}"> About </a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="row g-4">
                  <!-- Card START -->
                  <!-- Card END -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    {% endif %}
  {% endfor %}
{% endif %}

{% if posts %}
  {% for post in posts %}
    <main>
      <div class="container">
        <div class="card mb-4">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between">
              <div class="d-flex align-items-center">
                <div class="avatar avatar-story me-2">
                  <a href="#">
                    <img class="avatar-img rounded-circle" src="{{ post.author.userprofile.image.url }}" alt="">
                  </a>
                </div>
                <div>
                  <div class="nav nav-divider">
                    <h6 class="nav-item card-title mb-0">
                      <a href="{% url 'userpost' post.author.username %}">{{ post.author.get_full_name }}</a>
                    </h6>
                  </div>
                 <p class="mb-0 small text-muted">{{ post.time|date:"F j, Y" }}</p>

                </div>
              </div>
              <div class="dropdown">
                <a href="#" class="text-secondary btn btn-secondary-soft-hover py-1 px-2" id="cardFeedAction"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bi bi-three-dots"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="cardFeedAction">
                  {% if post.author == request.user %}
                    {% if post.is_deletable %}
                      <li><a class="dropdown-item" href="{% url "updatepost" post.id %}"><i
                            class="bi bi-pencil-square"></i> Edit Post</a></li>
                      <li><a class="dropdown-item" href="{% url "deletepost" post.id %}"><i class="bi bi-trash"></i>
                          Delete Post</a></li>
                    {% else %}
                      <li><a class="dropdown-item" href="#" disabled><i class="bi bi-exclamation-circle"></i> Cannot
                          delete this post</a></li>
                    {% endif %}
                  {% else %}
                    <li><a class="dropdown-item" href="#" disabled><i class="bi bi-exclamation-circle"></i> Not
                        Authorized</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>

          <div class="card-body">
            {% if post.image.url %}
              <p class="card-text mb-3">{{ post.content }}</p>
              <a href="{% url "detailpost" post.author.username post.id %}">
                <img class="card-img custom-img-height" src="{{ post.image.url }}" alt=''>
              </a>
            {% else %}
              <p class="card-text">{{ post.content }}</p>
            {% endif %}

            <div class="d-flex justify-content-between align-items-center mt-3">
              <div class="d-flex">
              <form id="like-form" method="POST" action="{% url 'like_post' post.author.username post.id %}">
    {% csrf_token %}
    <button type="submit" class="text-primary me-3" style="border: none; background-color: transparent;">
        <i class="bi bi-hand-thumbs-up"></i> Like ({{ post.like_set.count }})
    </button>
</form>
              </div>
              <div>
                <a href="#" class="text-secondary">
                  <i class="bi bi-share"></i> Share
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endfor %}
{% endif %}

<style>
  .custom-img-height {
    max-height: 100vh;
    width: auto;
    display: block;
    margin: auto;
  }
</style>
{% endblock body %}